# Generated by Django 3.0.3 on 2020-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_auto_20200227_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesland',
            name='name',
            field=models.CharField(choices=[('Burgenland', 'burgenland'), ('Niederösterreich', 'niederösterreich'), ('Oberösterreich', 'oberösterreich'), ('Wien', 'wien'), ('Steiermark', 'steiermark'), ('Tirol', 'tirol'), ('Kärnten', 'kärnten'), ('Salzburg', 'salzburg'), ('Vorarlberg', 'vorarlberg')], max_length=50),
        ),
    ]
