# Generated by Django 3.0.3 on 2020-02-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_auto_20200227_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesland',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
