# Generated by Django 3.0.3 on 2020-03-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_auto_20200227_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'municipalities'},
        ),
    ]
