# Generated by Django 2.2.5 on 2020-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='has_second_parameter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='must_have_reference_period',
            field=models.BooleanField(default=False),
        ),
    ]
