# Generated by Django 2.2.5 on 2020-02-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200216_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
