# Generated by Django 2.2.5 on 2020-02-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200219_1318'),
        ('products', '0002_auto_20200216_1636'),
    ]

    operations = [
    ]
