# Generated by Django 2.2.5 on 2020-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20200223_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('print_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('long_unit_name', models.CharField(max_length=100)),
                ('rounding_digits', models.IntegerField()),
                ('dtyope_out', models.CharField(max_length=10)),
                ('scale_factor', models.FloatField()),
                ('_FillValue', models.FloatField()),
            ],
        ),
    ]
