# Generated by Django 2.2.5 on 2020-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('print_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('print_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('print_name', models.CharField(max_length=100)),
            ],
        ),
    ]
