# Generated by Django 3.0.3 on 2020-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200225_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='print_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
