# Generated by Django 3.0.3 on 2020-02-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200228_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='season',
            name='print_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='season',
            name='datum_start',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='season',
            name='datum_end',
            field=models.CharField(max_length=10),
        ),
    ]
