# Generated by Django 3.0.3 on 2020-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200228_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
