# Generated by Django 3.0.3 on 2020-03-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputtype',
            name='otype',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
