# Generated by Django 3.0.3 on 2020-03-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_outputtype_otype'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='filename',
            field=models.CharField(default='test', max_length=256),
        ),
    ]
