# Generated by Django 3.0.3 on 2020-03-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_analysis_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_details',
            field=models.TextField(default='test'),
        ),
    ]
