# Generated by Django 3.0.3 on 2020-03-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_analysis_analysis_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='filename',
            field=models.CharField(default='', max_length=256),
        ),
    ]
