# Generated by Django 3.0.3 on 2020-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200304_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='request_post',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
