# Generated by Django 3.0.3 on 2020-03-05 09:57

from django.db import migrations, models
import products.storage


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200305_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='file',
            field=models.FileField(max_length=200, storage=products.storage.OverWriteStorage(), upload_to=''),
        ),
    ]
