# Generated by Django 3.0.3 on 2020-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_analysis_settings_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationperiod',
            name='enabled_parameters',
            field=models.CharField(default='', max_length=256),
        ),
    ]
